{% set name = "pytest-rerunfailures" %}
{% set version = "10.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e1e1bad51e07642c5bbab809fc1d4ec8eebcb7de86f90f1a26e6ef9de446697

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest >=5.3
    - python
    - setuptools >=40.0
    - wheel
  run:
    - pytest >=5.3
    - python
    - pip
    - setuptools >=40.0

test:
  imports:
    - pytest_rerunfailures
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures
  dev_url: https://github.com/pytest-dev/pytest-rerunfailures
  doc_url: https://github.com/pytest-dev/pytest-rerunfailures/blob/master/README.rst

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
