{% set name = "pytest-rerunfailures" %}
{% set version = "12.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 784f462fa87fe9bdf781d0027d856b47a4bfe6c12af108f6bd887057a917b48e

build:
  number: 0
  skip: True # [py<38]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest >=5.3
    - python
    - setuptools >=40.0
    - wheel
  run:
    - pytest >=5.3
    - python
    - pip
    - setuptools >=40.0

test:
  imports:
    - pytest_rerunfailures
  requires:
    - pip
    - py
  commands:
    - pip check

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures
  dev_url: https://github.com/pytest-dev/pytest-rerunfailures
  doc_url: https://github.com/pytest-dev/pytest-rerunfailures/blob/master/README.rst

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
