{% set name = "pytest-rerunfailures" %}
{% set version = "8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17c1236b9f8463f74a5df6c807f301c53c2ea1ab81b7509b7e23fab3b7cbe812

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest >=3.10
    - python
  run:
    - pytest >=3.10
    - python

test:
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
